name: Publish to GitHub Pages

on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Builds your repository with Antora
      - name: "Generate site using antora site action"
        uses: kameshsampath/antora-site-action@v0.2.4
        with:
          antora_playbook: antora-playbook.yml

      # Publish to GitHub Pages
      - name: Publish to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          # Build directory to deploy
          build_dir: build/site

          # Do not allow Jekyll to build your site
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}